In [2]:
import pandas as pd

df = pd.read_csv("insurance_claims.csv")

print(df.shape)
df.head()

(1000, 40)

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   str
 4   policy_state                 1000 non-null   str
 5   policy_csl                   1000 non-null   str
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   str
 11  insured_education_level      1000 non-null   str
 12  insured_occupation           1000 non-null   str
 13  insured_hobbies              1000 non-null   str
 14  insured_relationship         1000 non-null   str
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   str
 18  incident_type                1000 non-null   str
 19  collision_type               1000 non-null   str
 20  incident_severity            1000 non-null   str
 21  authorities_contacted        909 non-null    str
 22  incident_state               1000 non-null   str
 23  incident_city                1000 non-null   str
 24  incident_location            1000 non-null   str
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   str
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   str
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   str
 36  auto_model                   1000 non-null   str
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   str
 39  _c39                         0 non-null      float64
dtypes: float64(2), int64(17), str(21)
memory usage: 472.5 KB

In [4]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
months_as_customer,1000.0,NaN,NaN,NaN,203.954,115.113174,0.0,115.75,199.5,276.25,479.0
age,1000.0,NaN,NaN,NaN,38.948,9.140287,19.0,32.0,38.0,44.0,64.0
policy_number,1000.0,NaN,NaN,NaN,546238.648,257063.005276,100804.0,335980.25,533135.0,759099.75,999435.0
policy_bind_date,1000,951,2006-01-01,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
policy_state,1000,3,OH,352,NaN,NaN,NaN,NaN,NaN,NaN,NaN
policy_csl,1000,3,250/500,351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
policy_deductable,1000.0,NaN,NaN,NaN,1136.0,611.864673,500.0,500.0,1000.0,2000.0,2000.0
policy_annual_premium,1000.0,NaN,NaN,NaN,1256.40615,244.167395,433.33,1089.6075,1257.2,1415.695,2047.59
umbrella_limit,1000.0,NaN,NaN,NaN,1101000.0,2297406.598118,-1000000.0,0.0,0.0,0.0,10000000.0
insured_zip,1000.0,NaN,NaN,NaN,501214.488,71701.610941,430104.0,448404.5,466445.5,603251.0,620962.0
insured_sex,1000,2,FEMALE,537,NaN,NaN,NaN,NaN,NaN,NaN,NaN
insured_education_level,1000,7,JD,161,NaN,NaN,NaN,NaN,NaN,NaN,NaN
insured_occupation,1000,14,machine-op-inspct,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN
insured_hobbies,1000,20,reading,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN
insured_relationship,1000,6,own-child,183,NaN,NaN,NaN,NaN,NaN,NaN,NaN
capital-gains,1000.0,NaN,NaN,NaN,25126.1,27872.187708,0.0,0.0,0.0,51025.0,100500.0
capital-loss,1000.0,NaN,NaN,NaN,-26793.7,28104.096686,-111100.0,-51500.0,-23250.0,0.0,0.0
incident_date,1000,60,2015-02-02,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incident_type,1000,4,Multi-vehicle Collision,419,NaN,NaN,NaN,NaN,NaN,NaN,NaN
collision_type,1000,4,Rear Collision,292,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incident_severity,1000,4,Minor Damage,354,NaN,NaN,NaN,NaN,NaN,NaN,NaN
authorities_contacted,909,4,Police,292,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incident_state,1000,7,NY,262,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incident_city,1000,7,Springfield,157,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incident_location,1000,1000,9935 4th Drive,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incident_hour_of_the_day,1000.0,NaN,NaN,NaN,11.644,6.951373,0.0,6.0,12.0,17.0,23.0
number_of_vehicles_involved,1000.0,NaN,NaN,NaN,1.839,1.01888,1.0,1.0,1.0,3.0,4.0
property_damage,1000,3,?,360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bodily_injuries,1000.0,NaN,NaN,NaN,0.992,0.820127,0.0,0.0,1.0,2.0,2.0
witnesses,1000.0,NaN,NaN,NaN,1.487,1.111335,0.0,1.0,1.0,2.0,3.0
police_report_available,1000,3,?,343,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_claim_amount,1000.0,NaN,NaN,NaN,52761.94,26401.53319,100.0,41812.5,58055.0,70592.5,114920.0
injury_claim,1000.0,NaN,NaN,NaN,7433.42,4880.951853,0.0,4295.0,6775.0,11305.0,21450.0
property_claim,1000.0,NaN,NaN,NaN,7399.57,4824.726179,0.0,4445.0,6750.0,10885.0,23670.0
vehicle_claim,1000.0,NaN,NaN,NaN,37928.95,18886.252893,70.0,30292.5,42100.0,50822.5,79560.0
auto_make,1000,14,Saab,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
auto_model,1000,39,RAM,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
auto_year,1000.0,NaN,NaN,NaN,2005.103,6.015861,1995.0,2000.0,2005.0,2010.0,2015.0
fraud_reported,1000,2,N,753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
_c39,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
features = [
    "age",
    "months_as_customer",
    "policy_deductable",
    "policy_annual_premium",
    "umbrella_limit",
    "capital-gains",
    "capital-loss",
    "incident_severity",
    "number_of_vehicles_involved",
    "bodily_injuries"
]

In [6]:
target = "total_claim_amount"

In [7]:
numeric_cols = df.select_dtypes(include="number").columns

corr = df[numeric_cols].corr()["total_claim_amount"].sort_values(
    ascending=False
)

print(corr)

total_claim_amount             1.000000
vehicle_claim                  0.982773
property_claim                 0.810686
injury_claim                   0.805025
number_of_vehicles_involved    0.274278
incident_hour_of_the_day       0.217702
age                            0.069863
months_as_customer             0.062108
bodily_injuries                0.047093
policy_deductable              0.022839
capital-gains                  0.015980
policy_annual_premium          0.009094
witnesses                     -0.011114
policy_number                 -0.018009
insured_zip                   -0.033873
auto_year                     -0.035781
capital-loss                  -0.036060
umbrella_limit                -0.040344
_c39                                NaN
Name: total_claim_amount, dtype: float64

In [8]:
df[[
    "age",
    "months_as_customer",
    "policy_deductable",
    "policy_annual_premium",
    "umbrella_limit",
    "capital-gains",
    "capital-loss",
    "incident_hour_of_the_day",
    "number_of_vehicles_involved",
    "bodily_injuries",
    "witnesses",
    "auto_year",
    "total_claim_amount"
]].corr()["total_claim_amount"].sort_values(ascending=False)

total_claim_amount             1.000000
number_of_vehicles_involved    0.274278
incident_hour_of_the_day       0.217702
age                            0.069863
months_as_customer             0.062108
bodily_injuries                0.047093
policy_deductable              0.022839
capital-gains                  0.015980
policy_annual_premium          0.009094
witnesses                     -0.011114
auto_year                     -0.035781
capital-loss                  -0.036060
umbrella_limit                -0.040344
Name: total_claim_amount, dtype: float64

In [9]:
numeric_features = [
    "age",
    "months_as_customer",
    "policy_deductable",
    "policy_annual_premium",
    "number_of_vehicles_involved",
    "bodily_injuries",
    "witnesses",
    "incident_hour_of_the_day"
]

In [10]:
categorical_features = [
    "incident_type",
    "collision_type",
    "incident_severity",
    "property_damage",
    "police_report_available"
]

In [11]:
target = "total_claim_amount"

In [12]:
excluded = [
    "policy_number",
    "policy_bind_date",
    "insured_zip",
    "insured_hobbies",
    "incident_date",
    "incident_location",
    "injury_claim",
    "property_claim",
    "vehicle_claim",
    "_c39"
]

In [13]:
print("Missing values:")
print(df.isnull().sum())

print("\n'?' values:")
for col in df.select_dtypes(include="object").columns:
    count = (df[col] == "?").sum()
    if count > 0:
        print(col, ":", count)

Missing values:
months_as_customer                0
age                               0
policy_number                     0
policy_bind_date                  0
policy_state                      0
policy_csl                        0
policy_deductable                 0
policy_annual_premium             0
umbrella_limit                    0
insured_zip                       0
insured_sex                       0
insured_education_level           0
insured_occupation                0
insured_hobbies                   0
insured_relationship              0
capital-gains                     0
capital-loss                      0
incident_date                     0
incident_type                     0
collision_type                    0
incident_severity                 0
authorities_contacted            91
incident_state                    0
incident_city                     0
incident_location                 0
incident_hour_of_the_day          0
number_of_vehicles_involved       0
property_damage                   0
bodily_injuries                   0
witnesses                         0
police_report_available           0
total_claim_amount                0
injury_claim                      0
property_claim                    0
vehicle_claim                     0
auto_make                         0
auto_model                        0
auto_year                         0
fraud_reported                    0
_c39                           1000
dtype: int64

'?' values:
collision_type : 178
property_damage : 360
police_report_available : 343

C:\Users\ads2609025\AppData\Local\Temp\ipykernel_15008\2810773170.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [14]:
import numpy as np

# Remove completely empty column
df = df.drop(columns=["_c39"])

# Convert '?' to NaN
df = df.replace("?", np.nan)

# Check missing values again
print(df.isnull().sum()[df.isnull().sum() > 0])

collision_type             178
authorities_contacted       91
property_damage            360
police_report_available    343
dtype: int64

In [15]:
numeric_features = [
    "age",
    "months_as_customer",
    "policy_deductable",
    "policy_annual_premium",
    "number_of_vehicles_involved",
    "bodily_injuries",
    "witnesses",
    "incident_hour_of_the_day"
]

categorical_features = [
    "incident_type",
    "collision_type",
    "incident_severity",
    "property_damage",
    "police_report_available"
]

target = "total_claim_amount"

X = df[numeric_features + categorical_features]
y = df[target]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1000, 13)
y shape: (1000,)

In [16]:
from sklearn.model_selection import train_test_split

X_train_val, X_test, y_train_val, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_val,
    y_train_val,
    test_size=0.25,
    random_state=42
)

print("Training:", X_train.shape, y_train.shape)
print("Validation:", X_val.shape, y_val.shape)
print("Testing:", X_test.shape, y_test.shape)

Training: (600, 13) (600,)
Validation: (200, 13) (200,)
Testing: (200, 13) (200,)

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [18]:
from sklearn.preprocessing import OneHotEncoder

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [19]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])

In [20]:
print(preprocessor)

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'months_as_customer',
                                  'policy_deductable', 'policy_annual_premium',
                                  'number_of_vehicles_involved',
                                  'bodily_injuries', 'witnesses',
                                  'incident_hour_of_the_day']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['incident_type', 'collision_type',
                                  'incident_severity', 'property_damage',
                                  'police_report_available'])])

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

linear_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

In [22]:
linear_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'months_as_customer',
                                                   'policy_deductable',
                                                   'policy_annual_premium',
                                                   'number_of_vehicles_involved',
                                                   'bodily_injuries',
                                                   'witnesses',
                                                   'incident_hour_of_the_day']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['incident_type',
                                                   'collision_type',
                                                   'incident_severity',
                                                   'property_damage',
                                                   'police_report_available'])])),
                ('model', LinearRegression())])

In [23]:
y_train_pred = linear_model.predict(X_train)
y_val_pred = linear_model.predict(X_val)

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

train_mae = mean_absolute_error(y_train, y_train_pred)
train_mse = mean_squared_error(y_train, y_train_pred)
train_rmse = np.sqrt(train_mse)
train_r2 = r2_score(y_train, y_train_pred)

val_mae = mean_absolute_error(y_val, y_val_pred)
val_mse = mean_squared_error(y_val, y_val_pred)
val_rmse = np.sqrt(val_mse)
val_r2 = r2_score(y_val, y_val_pred)

print("===== TRAINING =====")
print("MAE :", train_mae)
print("MSE :", train_mse)
print("RMSE:", train_rmse)
print("R²  :", train_r2)

print("\n===== VALIDATION =====")
print("MAE :", val_mae)
print("MSE :", val_mse)
print("RMSE:", val_rmse)
print("R²  :", val_r2)

===== TRAINING =====
MAE : 10950.136163148418
MSE : 210026717.44261533
RMSE: 14492.298556219966
R²  : 0.7004045264422204

===== VALIDATION =====
MAE : 10216.817312059793
MSE : 197846127.64044076
RMSE: 14065.778600576676
R²  : 0.7141293493271643

In [25]:
from sklearn.linear_model import Ridge

ridge_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", Ridge(alpha=1.0))
])

In [26]:
ridge_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'months_as_customer',
                                                   'policy_deductable',
                                                   'policy_annual_premium',
                                                   'number_of_vehicles_involved',
                                                   'bodily_injuries',
                                                   'witnesses',
                                                   'incident_hour_of_the_day']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['incident_type',
                                                   'collision_type',
                                                   'incident_severity',
                                                   'property_damage',
                                                   'police_report_available'])])),
                ('model', Ridge())])

In [27]:
y_train_pred_ridge = ridge_model.predict(X_train)
y_val_pred_ridge = ridge_model.predict(X_val)

In [28]:
train_mae = mean_absolute_error(y_train, y_train_pred_ridge)
train_mse = mean_squared_error(y_train, y_train_pred_ridge)
train_rmse = np.sqrt(train_mse)
train_r2 = r2_score(y_train, y_train_pred_ridge)

val_mae = mean_absolute_error(y_val, y_val_pred_ridge)
val_mse = mean_squared_error(y_val, y_val_pred_ridge)
val_rmse = np.sqrt(val_mse)
val_r2 = r2_score(y_val, y_val_pred_ridge)

print("===== RIDGE TRAINING =====")
print("MAE :", train_mae)
print("MSE :", train_mse)
print("RMSE:", train_rmse)
print("R²  :", train_r2)

print("\n===== RIDGE VALIDATION =====")
print("MAE :", val_mae)
print("MSE :", val_mse)
print("RMSE:", val_rmse)
print("R²  :", val_r2)

===== RIDGE TRAINING =====
MAE : 10960.85311049543
MSE : 210398485.77781624
RMSE: 14505.119295538945
R²  : 0.6998742124336289

===== RIDGE VALIDATION =====
MAE : 10190.538822863447
MSE : 196308213.5616552
RMSE: 14011.003303177657
R²  : 0.7163515029959

In [29]:
alphas = [0.01, 0.1, 1, 10, 100]

for alpha in alphas:

    model = Pipeline([
        ("preprocessor", preprocessor),
        ("model", Ridge(alpha=alpha))
    ])

    model.fit(X_train, y_train)

    y_val_pred = model.predict(X_val)

    mae = mean_absolute_error(y_val, y_val_pred)
    mse = mean_squared_error(y_val, y_val_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_val, y_val_pred)

    print(f"Alpha: {alpha}")
    print(f"MAE : {mae:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R²  : {r2:.4f}")
    print("-" * 30)

Alpha: 0.01
MAE : 10216.02
RMSE: 14065.00
R²  : 0.7142
------------------------------
Alpha: 0.1
MAE : 10209.76
RMSE: 14058.26
R²  : 0.7144
------------------------------
Alpha: 1
MAE : 10190.54
RMSE: 14011.00
R²  : 0.7164
------------------------------
Alpha: 10
MAE : 10678.39
RMSE: 14151.59
R²  : 0.7106
------------------------------
Alpha: 100
MAE : 13549.46
RMSE: 16674.98
R²  : 0.5982
------------------------------

In [30]:
from sklearn.model_selection import cross_val_score

alphas = [0.01, 0.1, 1, 10, 100]

for alpha in alphas:
  
    model = Pipeline([
        ("preprocessor", preprocessor),
        ("model", Ridge(alpha=alpha))
    ])

    scores = cross_val_score(
        model,
        X_train_val,
        y_train_val,
        cv=5,
        scoring="r2"
    )

    print(f"Alpha: {alpha}")
    print("R² scores:", scores)
    print("Mean R²:", scores.mean())
    print("Std R² :", scores.std())
    print("-" * 40)

Alpha: 0.01
R² scores: [0.71084356 0.64233638 0.66936108 0.7164447  0.70972475]
Mean R²: 0.6897420950035895
Std R² : 0.02905269197638821
----------------------------------------
Alpha: 0.1
R² scores: [0.7110612  0.64227926 0.66926017 0.71665072 0.70956934]
Mean R²: 0.6897641378744468
Std R² : 0.029133916951703642
----------------------------------------
Alpha: 1
R² scores: [0.71236164 0.64147985 0.66803332 0.71807692 0.70790018]
Mean R²: 0.6895703831892863
Std R² : 0.029814730060346194
----------------------------------------
Alpha: 10
R² scores: [0.70369031 0.63053347 0.65212447 0.71212574 0.68957387]
Mean R²: 0.6776095711763436
Std R² : 0.031242166642499465
----------------------------------------
Alpha: 100
R² scores: [0.59746252 0.54167492 0.54905603 0.60008799 0.56434285]
Mean R²: 0.5705248643227907
Std R² : 0.024211828609064547
----------------------------------------

In [31]:
final_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", Ridge(alpha=0.1))
])

In [32]:
final_model.fit(X_train_val, y_train_val)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'months_as_customer',
                                                   'policy_deductable',
                                                   'policy_annual_premium',
                                                   'number_of_vehicles_involved',
                                                   'bodily_injuries',
                                                   'witnesses',
                                                   'incident_hour_of_the_day']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['incident_type',
                                                   'collision_type',
                                                   'incident_severity',
                                                   'property_damage',
                                                   'police_report_available'])])),
                ('model', Ridge(alpha=0.1))])

In [33]:
y_test_pred = final_model.predict(X_test)

In [34]:
test_mae = mean_absolute_error(y_test, y_test_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_rmse = np.sqrt(test_mse)
test_r2 = r2_score(y_test, y_test_pred)

print("===== FINAL TEST RESULTS =====")
print("MAE :", test_mae)
print("MSE :", test_mse)
print("RMSE:", test_rmse)
print("R²  :", test_r2)

===== FINAL TEST RESULTS =====
MAE : 10663.237301069335
MSE : 203518134.43329483
RMSE: 14265.978215085526
R²  : 0.6941886654891714

In [35]:
feature_names = final_model.named_steps["preprocessor"].get_feature_names_out()

coefficients = final_model.named_steps["model"].coef_

coef_df = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coefficients
})

coef_df["abs_coefficient"] = coef_df["coefficient"].abs()

coef_df = coef_df.sort_values(
    "abs_coefficient",
    ascending=False
)

print(coef_df.head(15))

                                        feature   coefficient  abs_coefficient
8    cat__incident_type_Multi-vehicle Collision  30241.514115     30241.514115
11             cat__incident_type_Vehicle Theft -29698.642793     29698.642793
9                 cat__incident_type_Parked Car -29638.259518     29638.259518
10  cat__incident_type_Single Vehicle Collision  29095.388195     29095.388195
4              num__number_of_vehicles_involved  -2263.622131      2263.622131
17            cat__incident_severity_Total Loss  -1453.068756      1453.068756
13           cat__collision_type_Rear Collision  -1203.996779      1203.996779
19                      cat__property_damage_NO  -1198.864654      1198.864654
20                     cat__property_damage_YES   1198.864654      1198.864654
5                          num__bodily_injuries   1136.928432      1136.928432
15          cat__incident_severity_Major Damage   1084.947557      1084.947557
12          cat__collision_type_Front Collision   1028.766210      1028.766210
0                                      num__age    817.478415       817.478415
2                        num__policy_deductable    550.220135       550.220135
6                                num__witnesses   -388.011224       388.011224

In [36]:
import joblib

joblib.dump(final_model, "insurance_ridge_model.pkl")

print("Model saved successfully!")

Model saved successfully!